targets:
  $default:
    builders:
      envied_generator|envied:
        enabled: true
        generate_for:
          include:
            - lib/env.dart
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/data/**
