name: Check code quality

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      # these env variables (but not their values) are required for build_runner
      SERVER_URL: ''
      SERVER_CHECK_VERSIONS_PATH: ''
      SERVER_DOWNLOAD_DATA_PATH: ''
      SERVER_MEDIA_PATH_PREFIX: ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          pub-cache: true

      - name: Create .env file
        run: cp .env.example .env
      - name: Install dependencies
        run: flutter pub get
      - name: Run build_runner
        run: dart run build_runner build
      - name: Verify generated files
        run: git diff --exit-code
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Run analysis
        run: dart analyze
      - name: Run tests
        run: flutter test
